<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CrewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $crewMappings = [
            ['movie_title' => 'Kill Bill: Vol. 1', 'person_name' => 'Quentin Tarantino', 'department' => 'Director'],
            ['movie_title' => 'Kill Bill: Vol. 1', 'person_name' => 'RZA', 'department' => 'Composer'],
            ['movie_title' => 'Kill Bill: Vol. 1', 'person_name' => 'Robert Richardson', 'department' => 'Cinematographer'],
            ['movie_title' => 'Kill Bill: Vol. 1', 'person_name' => 'Quentin Tarantino', 'department' => 'Writer'],
            ['movie_title' => 'Kill Bill: Vol. 1', 'person_name' => 'Sally Menke', 'department' => 'Editor'],
            ['movie_title' => 'Kill Bill: Vol. 1', 'person_name' => 'Kumiko Ogawa', 'department' => 'Costume Designer'],
            ['movie_title' => 'The Matrix', 'person_name' => 'Lana Wachowski', 'department' => 'Director'],
            ['movie_title' => 'The Matrix', 'person_name' => 'Lilly Wachowski', 'department' => 'Director'],
            ['movie_title' => 'The Matrix', 'person_name' => 'Lana Wachowski', 'department' => 'Writer'],
            ['movie_title' => 'The Matrix', 'person_name' => 'Lilly Wachowski', 'department' => 'Writer'],
            ['movie_title' => 'The Matrix', 'person_name' => 'Don Davis', 'department' => 'Composer'],
            ['movie_title' => 'The Matrix', 'person_name' => 'Bill Pope', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Matrix', 'person_name' => 'Zach Staenberg', 'department' => 'Editor'],
            ['movie_title' => 'The Matrix', 'person_name' => 'Kym Barrett', 'department' => 'Costume Designer'],
            ['movie_title' => 'The Lord of the Rings: The Fellowship of the Ring', 'person_name' => 'Peter Jackson', 'department' => 'Director'],
            ['movie_title' => 'The Lord of the Rings: The Fellowship of the Ring', 'person_name' => 'J.R.R. Tolkien', 'department' => 'Writer'],
            ['movie_title' => 'The Lord of the Rings: The Fellowship of the Ring', 'person_name' => 'Fran Walsh', 'department' => 'Writer'],
            ['movie_title' => 'The Lord of the Rings: The Fellowship of the Ring', 'person_name' => 'Philippa Boyens', 'department' => 'Writer'],
            ['movie_title' => 'The Lord of the Rings: The Fellowship of the Ring', 'person_name' => 'Howard Shore', 'department' => 'Composer'],
            ['movie_title' => 'The Lord of the Rings: The Fellowship of the Ring', 'person_name' => 'Andrew Lesnie', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Lord of the Rings: The Fellowship of the Ring', 'person_name' => 'John Gilbert', 'department' => 'Editor'],
            ['movie_title' => 'The Lord of the Rings: The Fellowship of the Ring', 'person_name' => 'Ngila Dickson', 'department' => 'Costume Designer'],
            ['movie_title' => 'Avatar', 'person_name' => 'James Cameron', 'department' => 'Director'],
            ['movie_title' => 'Avatar', 'person_name' => 'James Cameron', 'department' => 'Writer'],
            ['movie_title' => 'Avatar', 'person_name' => 'James Horner', 'department' => 'Composer'],
            ['movie_title' => 'Avatar', 'person_name' => 'Mauro Fiore', 'department' => 'Cinematographer'],
            ['movie_title' => 'Avatar', 'person_name' => 'John Refoua', 'department' => 'Editor'],
            ['movie_title' => 'Avatar', 'person_name' => 'Mayes C. Rubeo', 'department' => 'Costume Designer'],
            ['movie_title' => 'Joker', 'person_name' => 'Todd Phillips', 'department' => 'Director'],
            ['movie_title' => 'Joker', 'person_name' => 'Todd Phillips', 'department' => 'Writer'],
            ['movie_title' => 'Joker', 'person_name' => 'Scott Silver', 'department' => 'Writer'],
            ['movie_title' => 'Joker', 'person_name' => 'Hildur Guðnadóttir', 'department' => 'Composer'],
            ['movie_title' => 'Joker', 'person_name' => 'Lawrence Sher', 'department' => 'Cinematographer'],
            ['movie_title' => 'Joker', 'person_name' => 'Jeff Groth', 'department' => 'Editor'],
            ['movie_title' => 'Joker', 'person_name' => 'Mark Bridges', 'department' => 'Costume Designer'],
            ['movie_title' => 'Pulp Fiction', 'person_name' => 'Quentin Tarantino', 'department' => 'Director'],
            ['movie_title' => 'Pulp Fiction', 'person_name' => 'Quentin Tarantino', 'department' => 'Writer'],
            ['movie_title' => 'Pulp Fiction', 'person_name' => 'Roger Avary', 'department' => 'Writer'],
            ['movie_title' => 'Pulp Fiction', 'person_name' => 'Quentin Tarantino', 'department' => 'Composer'],
            ['movie_title' => 'Pulp Fiction', 'person_name' => 'Andrzej Sekula', 'department' => 'Cinematographer'],
            ['movie_title' => 'Pulp Fiction', 'person_name' => 'Sally Menke', 'department' => 'Editor'],
            ['movie_title' => 'Pulp Fiction', 'person_name' => 'Betsy Heimann', 'department' => 'Costume Design'],
            ['movie_title' => 'Interstellar', 'person_name' => 'Christopher Nolan', 'department' => 'Director'],
            ['movie_title' => 'Interstellar', 'person_name' => 'Jonathan Nolan', 'department' => 'Writer'],
            ['movie_title' => 'Interstellar', 'person_name' => 'Christopher Nolan', 'department' => 'Writer'],
            ['movie_title' => 'Interstellar', 'person_name' => 'Hans Zimmer', 'department' => 'Composer'],
            ['movie_title' => 'Interstellar', 'person_name' => 'Hoyte Van Hoytema', 'department' => 'Cinematographer'],
            ['movie_title' => 'Interstellar', 'person_name' => 'Lee Smith', 'department' => 'Editor'],
            ['movie_title' => 'Interstellar', 'person_name' => 'Mary Zophres', 'department' => 'Costume Designer'],
            ['movie_title' => 'Inception', 'person_name' => 'Christopher Nolan', 'department' => 'Director'],
            ['movie_title' => 'Inception', 'person_name' => 'Christopher Nolan', 'department' => 'Writer'],
            ['movie_title' => 'Inception', 'person_name' => 'Hans Zimmer', 'department' => 'Composer'],
            ['movie_title' => 'Inception', 'person_name' => 'Wally Pfister', 'department' => 'Cinematographer'],
            ['movie_title' => 'Inception', 'person_name' => 'Lee Smith', 'department' => 'Editor'],
            ['movie_title' => 'Inception', 'person_name' => 'Jeffrey Kurland', 'department' => 'Costume Designer'],
            ['movie_title' => 'Dune', 'person_name' => 'Denis Villeneuve', 'department' => 'Director'],
            ['movie_title' => 'Dune', 'person_name' => 'Jon Spaihts', 'department' => 'Writer'],
            ['movie_title' => 'Dune', 'person_name' => 'Denis Villeneuve', 'department' => 'Writer'],
            ['movie_title' => 'Dune', 'person_name' => 'Hans Zimmer', 'department' => 'Composer'],
            ['movie_title' => 'Dune', 'person_name' => 'Greig Fraser', 'department' => 'Cinematographer'],
            ['movie_title' => 'Dune', 'person_name' => 'Joe Walker', 'department' => 'Editor'],
            ['movie_title' => 'Dune', 'person_name' => 'Bob Morgan', 'department' => 'Costume Designer'],
            ['movie_title' => 'The Incredibles', 'person_name' => 'Brad Bird', 'department' => 'Director'],
            ['movie_title' => 'The Incredibles', 'person_name' => 'Brad Bird', 'department' => 'Writer'],
            ['movie_title' => 'The Incredibles', 'person_name' => 'Michael Giacchino', 'department' => 'Composer'],
            ['movie_title' => 'The Incredibles', 'person_name' => 'Andrew Jimenez', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Incredibles', 'person_name' => 'Stephen Schaffer', 'department' => 'Editor'],
            ['movie_title' => 'The Incredibles', 'person_name' => 'Animated', 'department' => 'Costume Designer'],
            ['movie_title' => 'Ratatouille', 'person_name' => 'Brad Bird', 'department' => 'Director'],
            ['movie_title' => 'Ratatouille', 'person_name' => 'Jan Pinkava', 'department' => 'Director'],
            ['movie_title' => 'Ratatouille', 'person_name' => 'Brad Bird', 'department' => 'Writer'],
            ['movie_title' => 'Ratatouille', 'person_name' => 'Jan Pinkava', 'department' => 'Writer'],
            ['movie_title' => 'Ratatouille', 'person_name' => 'Michael Giacchino', 'department' => 'Composer'],
            ['movie_title' => 'Ratatouille', 'person_name' => 'Harley Jessup', 'department' => 'Cinematographer'],
            ['movie_title' => 'Ratatouille', 'person_name' => 'Darren T. Holmes', 'department' => 'Editor'],
            ['movie_title' => 'Ratatouille', 'person_name' => 'Animated', 'department' => 'Costume Designer'],
            ['movie_title' => 'Coco', 'person_name' => 'Lee Unkrich', 'department' => 'Director'],
            ['movie_title' => 'Coco', 'person_name' => 'Adrian Molina', 'department' => 'Director'],
            ['movie_title' => 'Coco', 'person_name' => 'Lee Unkrich', 'department' => 'Writer'],
            ['movie_title' => 'Coco', 'person_name' => 'Matthew Aldrich', 'department' => 'Writer'],
            ['movie_title' => 'Coco', 'person_name' => 'Michael Giacchino', 'department' => 'Composer'],
            ['movie_title' => 'Coco', 'person_name' => 'Steve Bloom', 'department' => 'Editor'],
            ['movie_title' => 'Coco', 'person_name' => 'Harley Jessup', 'department' => 'Cinematographer'],
            ['movie_title' => 'Coco', 'person_name' => 'Animated', 'department' => 'Costume Designer'],
            ['movie_title' => 'Home Alone', 'person_name' => 'Chris Columbus', 'department' => 'Director'],
            ['movie_title' => 'Home Alone', 'person_name' => 'John Hughes', 'department' => 'Writer'],
            ['movie_title' => 'Home Alone', 'person_name' => 'John Williams', 'department' => 'Composer'],
            ['movie_title' => 'Home Alone', 'person_name' => 'Julio Macat', 'department' => 'Cinematographer'],
            ['movie_title' => 'Home Alone', 'person_name' => 'Raja Gosnell', 'department' => 'Editor'],
            ['movie_title' => 'Home Alone', 'person_name' => 'Jay Hurley', 'department' => 'Costume Designer'],
            ['movie_title' => 'The Truman Show', 'person_name' => 'Peter Weir', 'department' => 'Director'],
            ['movie_title' => 'The Truman Show', 'person_name' => 'Andrew Niccol', 'department' => 'Writer'],
            ['movie_title' => 'The Truman Show', 'person_name' => 'Burkhard von Dallwitz', 'department' => 'Composer'],
            ['movie_title' => 'The Truman Show', 'person_name' => 'Peter Biziou', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Truman Show', 'person_name' => 'William M. Anderson', 'department' => 'Editor'],
            ['movie_title' => 'The Truman Show', 'person_name' => 'Marilyn Matthews', 'department' => 'Costume Designer'],
            ['movie_title' => 'Midsommar', 'person_name' => 'Ari Aster', 'department' => 'Director'],
            ['movie_title' => 'Midsommar', 'person_name' => 'Ari Aster', 'department' => 'Writer'],
            ['movie_title' => 'Midsommar', 'person_name' => 'The Haxan Cloak', 'department' => 'Composer'],
            ['movie_title' => 'Midsommar', 'person_name' => 'Pawel Pogorzelski', 'department' => 'Cinematographer'],
            ['movie_title' => 'Midsommar', 'person_name' => 'Lucian Johnston', 'department' => 'Editor'],
            ['movie_title' => 'Midsommar', 'person_name' => 'Andrea Flesch', 'department' => 'Costume Designer'],
            ['movie_title' => 'The Lighthouse', 'person_name' => 'Robert Eggers', 'department' => 'Director'],
            ['movie_title' => 'The Lighthouse', 'person_name' => 'Robert Eggers', 'department' => 'Writer'],
            ['movie_title' => 'The Lighthouse', 'person_name' => 'Max Eggers', 'department' => 'Writer'],
            ['movie_title' => 'The Lighthouse', 'person_name' => 'Mark Korven', 'department' => 'Composer'],
            ['movie_title' => 'The Lighthouse', 'person_name' => 'Jarin Blaschke', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Lighthouse', 'person_name' => 'Louise Ford', 'department' => 'Editor'],
            ['movie_title' => 'The Lighthouse', 'person_name' => 'Linda Muir', 'department' => 'Costume Designer'],
            ['movie_title' => 'Us', 'person_name' => 'Jordan Peele', 'department' => 'Director'],
            ['movie_title' => 'Us', 'person_name' => 'Jordan Peele', 'department' => 'Writer'],
            ['movie_title' => 'Us', 'person_name' => 'Michael Abels', 'department' => 'Composer'],
            ['movie_title' => 'Us', 'person_name' => 'Mike Gioulakis', 'department' => 'Cinematographer'],
            ['movie_title' => 'Us', 'person_name' => 'Nicholas Monsour', 'department' => 'Editor'],
            ['movie_title' => 'Us', 'person_name' => 'Kym Barrett', 'department' => 'Costume Designer'],

            // New Movies
            ['movie_title' => 'Oldboy', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Oldboy', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Oldboy', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Oldboy', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Oldboy', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Oldboy', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'John Wick', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'John Wick', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'John Wick', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'John Wick', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'John Wick', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'John Wick', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Barbie', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Barbie', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Barbie', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Barbie', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Barbie', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Barbie', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Everything Everywhere All at Once', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Everything Everywhere All at Once', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Everything Everywhere All at Once', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Everything Everywhere All at Once', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Everything Everywhere All at Once', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Everything Everywhere All at Once', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Spirited Away', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Spirited Away', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Spirited Away', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Spirited Away', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Spirited Away', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Spirited Away', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Fantastic Mr. Fox', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Fantastic Mr. Fox', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Fantastic Mr. Fox', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Fantastic Mr. Fox', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Fantastic Mr. Fox', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Fantastic Mr. Fox', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Inside Out', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Inside Out', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Inside Out', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Inside Out', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Inside Out', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Inside Out', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'The Wolf of Wall Street', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'The Wolf of Wall Street', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'The Wolf of Wall Street', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'The Wolf of Wall Street', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Wolf of Wall Street', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'The Wolf of Wall Street', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Forrest Gump', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Forrest Gump', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Forrest Gump', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Forrest Gump', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Forrest Gump', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Forrest Gump', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'American Psycho', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'American Psycho', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'American Psycho', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'American Psycho', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'American Psycho', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'American Psycho', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Se7en', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Se7en', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Se7en', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Se7en', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Se7en', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Se7en', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Jackass Forever', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Jackass Forever', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Jackass Forever', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Jackass Forever', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Jackass Forever', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Jackass Forever', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Miss Americana', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Miss Americana', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Miss Americana', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Miss Americana', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Miss Americana', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Miss Americana', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Fire of Love', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Fire of Love', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Fire of Love', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Fire of Love', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Fire of Love', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Fire of Love', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'The Social Dilemma', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'The Social Dilemma', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'The Social Dilemma', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'The Social Dilemma', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Social Dilemma', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'The Social Dilemma', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Koyaanisqatsi', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Koyaanisqatsi', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Koyaanisqatsi', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Koyaanisqatsi', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Koyaanisqatsi', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Koyaanisqatsi', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Whiplash', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Whiplash', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Whiplash', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Whiplash', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Whiplash', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Whiplash', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Cruella', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Cruella', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Cruella', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Cruella', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Cruella', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Cruella', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Charlie and the Chocolate Factory', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Charlie and the Chocolate Factory', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Charlie and the Chocolate Factory', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Charlie and the Chocolate Factory', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Charlie and the Chocolate Factory', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Charlie and the Chocolate Factory', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'The Northman', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'The Northman', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'The Northman', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'The Northman', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Northman', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'The Northman', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Oppenheimer', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Oppenheimer', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Oppenheimer', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Oppenheimer', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Oppenheimer', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Oppenheimer', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => '1917', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => '1917', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => '1917', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => '1917', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => '1917', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => '1917', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Portrait of a Lady on Fire', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Portrait of a Lady on Fire', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Portrait of a Lady on Fire', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Portrait of a Lady on Fire', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Portrait of a Lady on Fire', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Portrait of a Lady on Fire', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'The Zone of Interest', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'The Zone of Interest', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'The Zone of Interest', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'The Zone of Interest', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Zone of Interest', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'The Zone of Interest', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Society of the Snow', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Society of the Snow', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Society of the Snow', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Society of the Snow', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Society of the Snow', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Society of the Snow', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Longlegs', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Longlegs', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Longlegs', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Longlegs', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Longlegs', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Longlegs', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Pearl', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Pearl', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Pearl', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Pearl', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Pearl', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Pearl', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Sound of Metal', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Sound of Metal', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Sound of Metal', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Sound of Metal', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Sound of Metal', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Sound of Metal', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'TÁR', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'TÁR', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'TÁR', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'TÁR', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'TÁR', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'TÁR', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Maestro', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Maestro', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Maestro', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Maestro', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Maestro', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Maestro', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Cold War', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Cold War', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Cold War', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Cold War', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Cold War', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Cold War', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Barbarian', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Barbarian', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Barbarian', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Barbarian', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Barbarian', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Barbarian', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'The Lobster', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'The Lobster', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'The Lobster', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'The Lobster', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Lobster', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'The Lobster', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Arrival', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Arrival', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Arrival', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Arrival', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Arrival', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Arrival', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Saltburn', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Saltburn', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Saltburn', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Saltburn', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Saltburn', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Saltburn', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Jojo Rabbit', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Jojo Rabbit', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Jojo Rabbit', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Jojo Rabbit', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Jojo Rabbit', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Jojo Rabbit', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Inglourious Basterds', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Inglourious Basterds', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Inglourious Basterds', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Inglourious Basterds', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Inglourious Basterds', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Inglourious Basterds', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Come and See', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Come and See', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Come and See', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Come and See', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Come and See', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Come and See', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Poor Things', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Poor Things', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Poor Things', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Poor Things', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Poor Things', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Poor Things', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'The Pianist', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'The Pianist', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'The Pianist', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'The Pianist', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Pianist', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'The Pianist', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Django Unchained', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Django Unchained', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Django Unchained', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Django Unchained', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Django Unchained', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Django Unchained', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'The Revenant', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'The Revenant', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'The Revenant', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'The Revenant', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Revenant', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'The Revenant', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'The Hateful Eight', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'The Hateful Eight', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'The Hateful Eight', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'The Hateful Eight', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Hateful Eight', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'The Hateful Eight', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'The Good, the Bad and the Ugly', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'The Good, the Bad and the Ugly', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'The Good, the Bad and the Ugly', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'The Good, the Bad and the Ugly', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Good, the Bad and the Ugly', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'The Good, the Bad and the Ugly', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'The Power of the Dog', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'The Power of the Dog', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'The Power of the Dog', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'The Power of the Dog', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'The Power of the Dog', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'The Power of the Dog', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Rango', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Rango', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Rango', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Rango', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Rango', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Rango', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Morbius', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'Morbius', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'Morbius', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'Morbius', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'Morbius', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'Morbius', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'IF', 'person_name' => 'The Director', 'department' => 'Director'],
            ['movie_title' => 'IF', 'person_name' => 'The Writer', 'department' => 'Writer'],
            ['movie_title' => 'IF', 'person_name' => 'The Composer', 'department' => 'Composer'],
            ['movie_title' => 'IF', 'person_name' => 'The Cinematographer', 'department' => 'Cinematographer'],
            ['movie_title' => 'IF', 'person_name' => 'The Editor', 'department' => 'Editor'],
            ['movie_title' => 'IF', 'person_name' => 'The Costume Designer', 'department' => 'Costume Designer'],

            ['movie_title' => 'Harry Potter and the Sorcerer\'s Stone', 'person_name' => 'Chris Columbus', 'department' => 'Director'],
            ['movie_title' => 'Harry Potter and the Sorcerer\'s Stone', 'person_name' => 'J.K. Rowling', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Sorcerer\'s Stone', 'person_name' => 'Steve Kloves', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Sorcerer\'s Stone', 'person_name' => 'John Williams', 'department' => 'Composer'],
            ['movie_title' => 'Harry Potter and the Sorcerer\'s Stone', 'person_name' => 'John Seale', 'department' => 'Cinematographer'],
            ['movie_title' => 'Harry Potter and the Sorcerer\'s Stone', 'person_name' => 'Richard Francis-Bruce', 'department' => 'Editor'],
            ['movie_title' => 'Harry Potter and the Sorcerer\'s Stone', 'person_name' => 'Judianna Makovsky', 'department' => 'Costume Designer'],

            ['movie_title' => 'Harry Potter and the Chamber of Secrets', 'person_name' => 'Chris Columbus', 'department' => 'Director'],
            ['movie_title' => 'Harry Potter and the Chamber of Secrets', 'person_name' => 'J.K. Rowling', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Chamber of Secrets', 'person_name' => 'Steve Kloves', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Chamber of Secrets', 'person_name' => 'John Williams', 'department' => 'Composer'],
            ['movie_title' => 'Harry Potter and the Chamber of Secrets', 'person_name' => 'Roger Pratt', 'department' => 'Cinematographer'],
            ['movie_title' => 'Harry Potter and the Chamber of Secrets', 'person_name' => 'Peter Honess', 'department' => 'Editor'],
            ['movie_title' => 'Harry Potter and the Chamber of Secrets', 'person_name' => 'Lindy Hemming', 'department' => 'Costume Designer'],

            ['movie_title' => 'Harry Potter and the Prisoner of Azkaban', 'person_name' => 'Alfonso Cuarón', 'department' => 'Director'],
            ['movie_title' => 'Harry Potter and the Prisoner of Azkaban', 'person_name' => 'J.K. Rowling', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Prisoner of Azkaban', 'person_name' => 'Steve Kloves', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Prisoner of Azkaban', 'person_name' => 'John Williams', 'department' => 'Composer'],
            ['movie_title' => 'Harry Potter and the Prisoner of Azkaban', 'person_name' => 'Michael Seresin', 'department' => 'Cinematographer'],
            ['movie_title' => 'Harry Potter and the Prisoner of Azkaban', 'person_name' => 'Alexandra D. Berner', 'department' => 'Editor'],
            ['movie_title' => 'Harry Potter and the Prisoner of Azkaban', 'person_name' => 'Jany Temime', 'department' => 'Costume Designer'],

            ['movie_title' => 'Harry Potter and the Goblet of Fire', 'person_name' => 'Mike Newell', 'department' => 'Director'],
            ['movie_title' => 'Harry Potter and the Goblet of Fire', 'person_name' => 'J.K. Rowling', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Goblet of Fire', 'person_name' => 'Steve Kloves', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Goblet of Fire', 'person_name' => 'Patrick Doyle', 'department' => 'Composer'],
            ['movie_title' => 'Harry Potter and the Goblet of Fire', 'person_name' => 'Roger Pratt', 'department' => 'Cinematographer'],
            ['movie_title' => 'Harry Potter and the Goblet of Fire', 'person_name' => 'Mick Audsley', 'department' => 'Editor'],
            ['movie_title' => 'Harry Potter and the Goblet of Fire', 'person_name' => 'Jany Temime', 'department' => 'Costume Designer'],

            ['movie_title' => 'Harry Potter and the Order of the Phoenix', 'person_name' => 'David Yates', 'department' => 'Director'],
            ['movie_title' => 'Harry Potter and the Order of the Phoenix', 'person_name' => 'J.K. Rowling', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Order of the Phoenix', 'person_name' => 'Michael Goldenberg', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Order of the Phoenix', 'person_name' => 'Nicholas Hooper', 'department' => 'Composer'],
            ['movie_title' => 'Harry Potter and the Order of the Phoenix', 'person_name' => 'Sławomir Idziak', 'department' => 'Cinematographer'],
            ['movie_title' => 'Harry Potter and the Order of the Phoenix', 'person_name' => 'Mark Day', 'department' => 'Editor'],
            ['movie_title' => 'Harry Potter and the Order of the Phoenix', 'person_name' => 'Jany Temime', 'department' => 'Costume Designer'],

            ['movie_title' => 'Harry Potter and the Half-Blood Prince', 'person_name' => 'David Yates', 'department' => 'Director'],
            ['movie_title' => 'Harry Potter and the Half-Blood Prince', 'person_name' => 'J.K. Rowling', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Half-Blood Prince', 'person_name' => 'Steve Kloves', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Half-Blood Prince', 'person_name' => 'Nicholas Hooper', 'department' => 'Composer'],
            ['movie_title' => 'Harry Potter and the Half-Blood Prince', 'person_name' => 'Bruno Delbonnel', 'department' => 'Cinematographer'],
            ['movie_title' => 'Harry Potter and the Half-Blood Prince', 'person_name' => 'Mark Day', 'department' => 'Editor'],
            ['movie_title' => 'Harry Potter and the Half-Blood Prince', 'person_name' => 'Jany Temime', 'department' => 'Costume Designer'],

            ['movie_title' => 'Harry Potter and the Deathly Hallows – Part 1', 'person_name' => 'David Yates', 'department' => 'Director'],
            ['movie_title' => 'Harry Potter and the Deathly Hallows – Part 1', 'person_name' => 'J.K. Rowling', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Deathly Hallows – Part 1', 'person_name' => 'Steve Kloves', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Deathly Hallows – Part 1', 'person_name' => 'Alexandre Desplat', 'department' => 'Composer'],
            ['movie_title' => 'Harry Potter and the Deathly Hallows – Part 1', 'person_name' => 'Eduardo Serra', 'department' => 'Cinematographer'],
            ['movie_title' => 'Harry Potter and the Deathly Hallows – Part 1', 'person_name' => 'Mark Day', 'department' => 'Editor'],
            ['movie_title' => 'Harry Potter and the Deathly Hallows – Part 1', 'person_name' => 'Jany Temime', 'department' => 'Costume Designer'],

            ['movie_title' => 'Harry Potter and the Deathly Hallows – Part 2', 'person_name' => 'David Yates', 'department' => 'Director'],
            ['movie_title' => 'Harry Potter and the Deathly Hallows – Part 2', 'person_name' => 'J.K. Rowling', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Deathly Hallows – Part 2', 'person_name' => 'Steve Kloves', 'department' => 'Writer'],
            ['movie_title' => 'Harry Potter and the Deathly Hallows – Part 2', 'person_name' => 'Alexandre Desplat', 'department' => 'Composer'],
            ['movie_title' => 'Harry Potter and the Deathly Hallows – Part 2', 'person_name' => 'Eduardo Serra', 'department' => 'Cinematographer'],
            ['movie_title' => 'Harry Potter and the Deathly Hallows – Part 2', 'person_name' => 'Mark Day', 'department' => 'Editor'],
            ['movie_title' => 'Harry Potter and the Deathly Hallows – Part 2', 'person_name' => 'Jany Temime', 'department' => 'Costume Designer'],
        ];

        foreach ($crewMappings as $mapping) {
            //Retrieve Movie ID
            $movie = DB::table('movie')->where('title', $mapping['movie_title'])->first();

            //Retrieve Person ID
            $person = DB::table('person')->where('name', $mapping['person_name'])->first();

            //Retrieve Department ID
            $department = DB::table('department')->where('name', $mapping['department'])->first();

            //Add MovieID, PersonID and character name
            if ($movie && $person && $department) {
                DB::table('crew')->updateOrInsert([
                    'movie_id' => $movie->id,
                    'person_id' => $person->id,
                    'department_id' => $department->id,
                ]);
            }
        }
    }
}
