<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PersonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['name' => 'Quentin Tarantino', 'birthday' => '1963-03-27', 'biography' => 'Quentin Jerome Tarantino was born in Knoxville, Tennessee. His father, Tony Tarantino, is an Italian-American actor and musician from New York, and his mother, Connie (McHugh), is a nurse from Tennessee. Quentin moved with his mother to Torrance, California, when he was four years old.'],
            ['name' => 'Uma Thurman', 'birthday' => '1970-04-29', 'biography' => 'Uma Karuna Thurman was born in Boston, Massachusetts, into a highly unorthodox and internationally-minded family. She is the daughter of Nena Thurman (née Birgitte Caroline von Schlebrügge), a fashion model and socialite who now runs a mountain retreat, and of Robert Thurman (Robert Alexander Farrar Thurman), a professor and academic who is one of the nation\'s foremost Buddhist scholars. Uma\'s mother was born in Mexico City, Mexico, to a German father and a Swedish mother (who herself was of Swedish, Danish, and German descent). Uma\'s father, a New Yorker, has English, Scots-Irish, Scottish, and German ancestry. Uma grew up in Amherst, Massachusetts, where her father worked at Amherst College.'],
            ['name' => 'David Carradine', 'birthday' => '1936-12-08', 'biography' => 'David Carradine was born in Hollywood, California, the eldest son of legendary character actor John Carradine, and his wife, Ardanelle Abigail (McCool). He was a member of an acting family that included brothers Keith Carradine and Robert Carradine as well as his daughters Calista Carradine and Kansas Carradine, and nieces Ever Carradine and Martha Plimpton.'],
            ['name' => 'Daryl Hannah', 'birthday' => '1960-12-03', 'biography' => 'Daryl Christine Hannah was born and raised in Chicago, Illinois. She is the daughter of Susan Jeanne (Metzger), a schoolteacher and later a producer, and Donald Christian Hannah, who owned a tugboat/barge company. Her stepfather was music journalist/promoter Jerrold Wexler. Her siblings are Page Hannah, Don Hannah and Tanya Wexler. She has Scottish, Norwegian, Danish, Irish, English, and German ancestry.'],
            ['name' => 'RZA', 'birthday' => '1969-07-05', 'biography' => "Robert Fitzgerald Diggs better known by his stage name the RZA, is an American rapper, actor, filmmaker, and record producer. He is the de facto leader of the hip hop group Wu-Tang Clan, having produced most albums for the group and its respective members. He is a cousin of two other original Wu-Tang Clan members: GZA and Ol' Dirty Bastard. He has also released solo albums under the alter-ego Bobby Digital, along with executive producing credits for side projects. After forming the Wu-Tang Clan, RZA was a founding member of the horror-core group Gravediggaz, where he went by the name The RZArector."],
            ['name' => 'Robert Richardson', 'birthday' => '1955-08-27', 'biography' => "Robert Richardson has won three Academy Awards and earned seven Academy Award nominations for his cinematography. His work on director Oliver Stone's JFK earned him his first Oscar. His second and third came with The Aviator and Hugo directed by Martin Scorsese. These two films also garnered him BAFTA nominations for Best Cinematographer."],
            ['name' => 'Sally Menke', 'birthday' => '1953-12-17', 'biography' => "Sally Menke was born on December 17, 1953 in Mineola, New York, USA. She was an editor and producer, known for Kill Bill: Vol. 1 (2003), Kill Bill: Vol. 2 (2004) and Inglourious Basterds (2009). She was married to Dean Parisot. She died on September 27, 2010 in Los Angeles, California, USA."],
            ['name' => 'Kumiko Ogawa', 'birthday' => '1980-09-21', 'biography' => "Kumiko Ogawa is known for Kill Bill: Vol. 1 (2003), Kill Bill: Vol. 2 (2004) and Kill Bill: The Whole Bloody Affair (2006)."],
            ['name' => 'Lana Wachowski', 'birthday' => '1965-06-21', 'biography' => "Lana Wachowski and her sister Lilly Wachowski, also known as the Wachowskis, are the duo behind such ground-breaking movies as The Matrix (1999) and Cloud Atlas (2012). "],
            ['name' => 'Lilly Wachowski', 'birthday' => '1967-12-29', 'biography' => "Director, writer, and producer Lilly Wachowski was born in 1967 in Chicago, the daughter of Lynne, a nurse and painter, and Ron, a businessman. Lilly was educated at Kellogg Elementary School in Chicago, before moving on to Whitney M. Young High School. After graduating from high school, she attended Emerson College in Boston but dropped out."],
            ['name' => 'Keanu Reeves', 'birthday' => '1964-09-02', 'biography' => "Keanu Charles Reeves, whose first name means \"cool breeze over the mountains\" in Hawaiian, was born September 2, 1964 in Beirut, Lebanon. He is the son of Patric Reeves, a showgirl and costume designer, and Samuel Nowlin Reeves, a geologist. Keanu's father was born in Hawaii, of Native Hawaiian and Chinese ancestry while Keanu's mother is originally from Essex England. After his parents' marriage dissolved, Keanu moved with his mother and younger sister, Kim Reeves, to New York City, then Toronto.  In high school, Reeves was lukewarm toward academics but took a keen interest in ice hockey (as team goalie, he earned the nickname \"The Wall\") and drama. He eventually dropped out of school to pursue an acting career."],
            ['name' => 'Laurence Fishburne', 'birthday' => '1961-07-30', 'biography' => "Critically hailed for his forceful, militant, authoritative figures and one of Hollywood's most talented and versatile performers, Laurence (John) Fishburne III has been the recipient of numerous awards, including a number of NAACP Image honors."],
            ['name' => 'Carrie-Anne Moss', 'birthday' => '1967-08-21', 'biography' => "Carrie-Anne Moss was born and raised in Vancouver, Canada. At age 20, after studying at the American Academy of Dramatic Arts, she moved to Europe to pursue a career in modeling. While in Spain she was cast in the TV show Dark Justice which was produced in Barcelona for its first season and Los Angeles for its second. Once in LA, Carrie-Anne was cast in other series regular opportunities like Matrix with Nick Mancuso (which coincidentally presaged the movie that would later make her famous), and then Aaron Spelling's Models Inc."],
            ['name' => 'Don Davis', 'birthday' => '1957-02-04', 'biography' => "Donald Davis is an American film composer and conductor who is known for composing the music of The Matrix trilogy, Enter the Matrix, The Animatrix, SeaQuest 2032, the Beauty and the Beast television series and Jurassic Park III. He did orchestration for films composed by James Horner, Randy Newman and Alan Silvestri."],
            ['name' => 'Bill Pope', 'birthday' => '1952-06-19', 'biography' => "Bill Pope was born on June 19, 1952 in Bowling Green, Kentucky, USA. He is a cinematographer and director, known for The Matrix (1999), The Jungle Book (2016) and Spider-Man 2 (2004). He is married to Sharon Oreck. They have one child."],
            ['name' => 'Zach Staenberg', 'birthday' => '1954-01-10', 'biography' => "Zach Staenberg was born in 1954 in the USA. He is an editor and producer, known for The Matrix (1999), In Time (2011) and Nowhere to Run (1993)."],
            ['name' => 'Kym Barrett', 'birthday' => '1970-07-19', 'biography' => "Kym Barrett is an award-winning costume designer known for her iconic work on The Matrix trilogy. She began her career with Romeo & Juliet (1996) and later collaborated with Lana and Andy Wachowski on films like Speed Racer, Cloud Atlas, and Jupiter Ascending. Barrett has worked across a range of genres, including fantasy, action, and science fiction, and designed for notable productions like The Tempest at the Met and the 2014 Winter Olympics ceremonies."], 
            ['name' => 'Peter Jackson', 'birthday' => '1961-10-31', 'biography' => "Sir Peter Jackson made history with The Lord of the Rings trilogy, becoming the first person to direct three major feature films simultaneously. As a follow up to The Lord of the Rings trilogy, in 2005, Jackson directed, wrote, and produced King Kong, for Universal Pictures. The film grossed over $500 million and won three Oscars®."],
            ['name' => 'J.R.R. Tolkien', 'birthday' => '1892-01-03', 'biography' => "English writer, scholar and philologist. He wrote Lord of the Rings over a period of about 14 years."],
            ['name' => 'Fran Walsh', 'birthday' => '1959-01-10', 'biography' => "Fran Walsh is a New Zealand writer and wife of New Zealand film director Peter Jackson. She co-wrote The Lord of the Rings film trilogy, which is seen by many as Jackson's magnum opus and one of the most significant film series ever made. She also wrote The Hobbit trilogy, a prequel to Jackson's Lord of the Rings trilogy, King Kong, Mortal Engines, The Frighteners, Heavenly Creatures, The Lovely Bones and Meet the Feebles."],
            ['name' => 'Philippa Boyens', 'birthday' => '1974-10-20', 'biography' => "Philippa Boyens is a New Zealand writer and producer who has co-written several of Peter Jackson's films. She co-wrote the Academy Award winning Lord of the Rings trilogy, the Hobbit trilogy which is a prequel to the Lord of the Rings films, The Lovely Bones, Mortal Engines, and the 2005 remake of King Kong. She also co-produced District 9."],
            ['name' => 'Elijah Wood', 'birthday' => '1981-01-28', 'biography' => "Elijah Wood is an American actor best known for portraying Frodo Baggins in Peter Jackson's blockbuster Lord of the Rings film trilogy. In addition to reprising the role in The Hobbit series, Wood also played Ryan in the FX television comedy Wilfred (2011) and voiced Beck in the Disney XD animated television series Tron: Uprising (2012)."],
            ['name' => 'Ian McKellen', 'birthday' => '1939-05-25', 'biography' => "Widely regarded as one of the greatest stage and screen actors both in his native Great Britain and internationally, twice nominated for the Oscar and recipient of every major theatrical award in the UK and US, Ian Murray McKellen was born on May 25, 1939 in Burnley, Lancashire, England, to Margery Lois (Sutcliffe) and Denis Murray McKellen, a civil engineer and lay preacher. He is of Scottish, Northern Irish, and English descent."],
            ['name' => 'Orlando Bloom', 'birthday' => '1977-01-13', 'biography' => "Orlando Jonathan Blanchard Copeland Bloom was born on January 13, 1977 in Canterbury, Kent, England. His mother, Sonia Constance Josephine Bloom (née Copeland), was born in Kolkata, India, to an English family then-resident there."],
            ['name' => 'Howard Shore', 'birthday' => '1946-10-18', 'biography' => "Howard Shore is a Canadian composer, born in Toronto. He was born in a Jewish family. He started studying music when 8-years-old, and played as a member of bands by the time he was 13-years-old. He was interested in a professional career in music as a teenager. He studied music at the Berklee College of Music, a college of contemporary music located in Boston."],
            ['name' => 'Andrew Lesnie', 'birthday' => '1956-01-01', 'biography' => "Andrew Lesnie was an Australian cinematographer who frequently worked with Peter Jackson. He did the photography for The Lord of the Rings and The Hobbit film trilogies. He also did the photography for Babe, King Kong, Rise of the Planet of the Apes, I Am Legend and The Lovely Bones. He passed away in April 2015 due to a heart attack."],
            ['name' => 'John Gilbert', 'birthday' => '1960-09-22', 'biography' => "John Gilbert, an Academy Award and BAFTA-winning film editor, is known for his work on Hacksaw Ridge (2016). A native of New Zealand, Gilbert has edited 23 feature films, including The Lord of the Rings: The Fellowship of the Ring, for which he received a Satellite Award and Academy Award nomination. He also edited Crush, which was nominated for the Palme d'Or at Cannes. Gilbert's recent work includes 355 (2022) and Adrift (2018), and he is currently editing Damsel for Netflix."],
            ['name' => 'Ngila Dickson', 'birthday' => '1958-06-20', 'biography' => "Ngila Dickson was born in 1958 in Dunedin, New Zealand. She is a costume designer and actress, known for The Lord of the Rings: The Fellowship of the Ring (2001), The Lord of the Rings: The Return of the King (2003) and The Last Samurai (2003). She is married to Hamish Keith."],
            ['name' => 'James Cameron', 'birthday' => '1954-08-16', 'biography' => "James Francis Cameron was born on August 16, 1954 in Kapuskasing, Ontario, Canada. He moved to the United States in 1971. The son of an engineer, he majored in physics at California State University before switching to English, and eventually dropping out. He then drove a truck to support his screenwriting ambition. James Cameron is now one of the most sought-after directors in Hollywood."],
            ['name' => 'Sam Worthington', 'birthday' => '1976-08-02', 'biography' => "Sam Worthington, born in 1976 in England and raised in Australia, is known for his roles in Avatar (2009), Terminator Salvation (2009), and Clash of the Titans (2010). He won an AFI Award for Somersault (2004) and co-founded Full Clip Productions in 2010."],
            ['name' => 'Zoe Saldana', 'birthday' => '1978-06-19', 'biography' => "Zoe Saldana, born in 1978 in New Jersey, trained in dance in the Dominican Republic before moving back to the U.S. at 17. She gained fame with her role in Center Stage (2000) and quickly became known for her work in major films, earning praise from industry leaders."],
            ['name' => 'Sigourney Weaver', 'birthday' => '1949-10-08', 'biography' => "Sigourney Weaver, a Yale-trained actress, is known for iconic roles in Alien, Gorillas in the Mist, and Avatar: The Way of Water. With a career spanning 50 years, she has earned multiple awards, excelled in film, stage, and TV, and is an advocate for environmental and social causes."],
            ['name' => 'James Horner', 'birthday' => '1953-08-14', 'biography' => "James Horner, acclaimed composer of over 75 films, rose to fame with Star Trek II: The Wrath of Khan (1982). Known for collaborations with top directors, he also composed classical works. Horner tragically died in a plane crash in 2015 at 61."],
            ['name' => 'Mauro Fiore', 'birthday' => '1964-11-15', 'biography' => "Mauro Fiore was born on November 15, 1964 in Marzi, Calabria, Italy. He is a cinematographer, known for Avatar (2009), Training Day (2001) and The Island (2005). He has been married to Christine Vollmer since 2000. They have three children."],
            ['name' => 'John Refoua', 'birthday' => '1960-08-20', 'biography' => "John Refoua was born on 20 August 1960 in Tehran, Iran. He was an editor and producer, known for Avatar (2009), Avatar: The Way of Water (2022) and Geostorm (2017). He was married to Serena Bell Refoua. He died on 14 May 2023."],
            ['name' => 'Mayes C. Rubeo', 'birthday' => '1962-03-12', 'biography' => "Mayes C. Rubeo is a costume designer known for her work on Apocalypto (2006), Avatar (2009), Thor: Ragnarok (2017), and Warcraft (2016). Born in Mexico City, she trained at LATTC and UCLA. Rubeo has collaborated with directors like Mel Gibson and Zhang Yimou, and her work blends traditional craft with modern technology. Her designs have been featured in international exhibitions, and she is a member of the Academy of Motion Picture Arts and Sciences."],
            ['name' => 'Todd Phillips', 'birthday' => '1970-12-20', 'biography' => "Todd Phillips is an American director, producer, and screenwriter known for his work in comedy and drama. After studying film at NYU, he gained recognition with his documentaries Hated (1994) and Frat House (1998). Phillips made his feature film debut with the teen comedy Road Trip (2000), followed by hits like Old School (2003) and The Hangover (2009), which led to sequels and further success. He also directed War Dogs (2016) and Joker (2019), the latter earning widespread acclaim and several award nominations for Phillips and star Joaquin Phoenix. Phillips has built a career spanning comedy and drama, with a knack for creating films that blend humor with memorable moments."],
            ['name' => 'Scott Silver', 'birthday' => '1972-01-02', 'biography' => "Scott Silver is known for Joker (2019), The Fighter (2010) and Johns (1996)."],
            ['name' => 'Joaquin Phoenix', 'birthday' => '1974-10-28', 'biography' => "Joaquin Phoenix, born in Puerto Rico, began acting at a young age, first gaining recognition in Parenthood (1989). After his brother River's tragic death in 1993, he returned to acting with roles in To Die For (1995) and Inventing the Abbotts (1997). Phoenix became a star with Gladiator (2000), earning an Academy Award nomination. He later received another Oscar nod for Walk the Line (2005) and won a Grammy for the soundtrack. Phoenix continued to shine in films like The Master (2012) and Joker (2019), becoming known for his versatile performances."],
            ['name' => 'Robert De Niro', 'birthday' => '1943-08-17', 'biography' => "Robert De Niro, born on August 17, 1943, in New York City, is a legendary actor known for roles in Mean Streets (1973), The Godfather Part II (1974), and Raging Bull (1980), for which he won an Academy Award. He earned multiple nominations for films like Taxi Driver (1976) and The Deer Hunter (1978). De Niro has also directed films like A Bronx Tale (1993) and won the AFI Lifetime Achievement Award in 2003. He remains active in film, continuing to work into his 70s."],
            ['name' => 'Zazie Beetz', 'birthday' => '1991-06-01', 'biography' => "Zazie Beetz (born c. 1991) is a German-American actress known for Atlanta (2016), Deadpool 2 (2018), Joker (2019), and Nine Days (2020). Born in Berlin to a German father and African-American mother, she grew up in New York. Beetz studied French at Skidmore College and currently resides in New York."],
            ['name' => 'Hildur Guðnadóttir', 'birthday' => '1982-09-04', 'biography' => "Hildur Guðnadóttir was born on September 4, 1982 in Iceland. She is a composer, known for Joker (2019), Women Talking (2022) and Tár (2022). She is married to Sam Slater. They have one child."],
            ['name' => 'Lawrence Sher', 'birthday' => '1971-02-04', 'biography' => "Lawrence Sher was born in Teaneck, New Jersey, USA. He is a cinematographer and director, known for Joker (2019), The Hangover (2009) and Garden State (2004)."],
            ['name' => 'Jeff Groth', 'birthday' => '1969-09-13', 'biography' => "Jeff Groth is known for Joker (2019), The Gray Man (2022) and Joker: Folie à Deux (2024)."],
            ['name' => 'Mark Bridges', 'birthday' => '1964-04-16', 'biography' => "Mark Bridges was born in Niagara Falls, New York, USA. He is known for The Artist (2011), Phantom Thread (2017) and Inherent Vice (2014)."],
            ['name' => 'Roger Avary', 'birthday' => '1965-08-23', 'biography' => "Roger Avary is an award-winning filmmaker known for co-writing Pulp Fiction (1994) with Quentin Tarantino, for which he won an Academy Award. He also wrote and directed Killing Zoe (1994) and The Rules of Attraction (2002), and adapted Silent Hill (2006) and Beowulf (2007). In 2017, he directed Lucky Day and La voix humaine. Avary splits his time between Los Angeles, Paris, and Toronto."],
            ['name' => 'John Travolta', 'birthday' => '1954-02-18', 'biography' => "John Travolta, born February 18, 1954, in Englewood, New Jersey, is a renowned actor known for Saturday Night Fever (1977), Grease (1978), Pulp Fiction (1994), and Hairspray (2007). He has earned two Oscar nominations and a Golden Globe. A passionate aviator, he holds multiple jet licenses and is active in charity work through the Jett Travolta Foundation."],
            ['name' => 'Samuel L. Jackson', 'birthday' => '1948-12-21', 'biography' => "Samuel L. Jackson, born December 21, 1948, in Washington, D.C., is an iconic actor and producer, known for roles in Die Hard with a Vengeance (1995), Pulp Fiction (1994), The Avengers (2012), and Star Wars. He became famous in the 1990s, notably in collaborations with director Quentin Tarantino. Jackson also portrays Nick Fury in the Marvel Cinematic Universe and has voiced characters in The Incredibles and Afro Samurai. His portrayal of Jules Winnfield in Pulp Fiction earned him an Oscar nomination."],
            ['name' => 'Andrzej Sekula', 'birthday' => '1960-12-19', 'biography' => "Andrzej Sekula was born in Wroclaw, Dolnoslaskie, Poland. He is a cinematographer and director, known for Pulp Fiction (1994), American Psycho (2000) and Reservoir Dogs (1992)."],
            ['name' => 'Betsy Heimann', 'birthday' => '1961-05-15', 'biography' => "Betsy Heimann was born in Chicago, Illinois, USA. She is known for Almost Famous (2000), Pulp Fiction (1994) and The Tomorrow War (2021)."],
            ['name' => 'Christopher Nolan', 'birthday' => '1970-07-30', 'biography' => "Sir Christopher Nolan, born in London, England, is a renowned filmmaker known for his nonlinear storytelling. He began making short films as a child and later studied English Literature at University College London. His career took off with Memento (2000), earning him Academy Award and Golden Globe nominations. Nolan revived the Batman franchise with Batman Begins (2005) and achieved massive success with The Dark Knight (2008), Inception (2010), and Interstellar (2014). In 2017, Dunkirk earned him his first Best Director nomination. Nolan's Oppenheimer (2023) was a cultural phenomenon and earned him multiple awards, including his first Oscars. Nolan resides in Los Angeles with his wife, Dame Emma Thomas, and they run the production company Syncopy. He will be knighted in March 2024."],
            ['name' => 'Jonathan Nolan', 'birthday' => '1976-06-06', 'biography' => "Jonathan Nolan attended Loyola Academy in Wilmette, Illinois, graduating in 1994, and went on to graduate from Georgetown University in Washington, D.C. in 1999 with a major in English. Shortly after graduating, he worked as a production assistant on Memento (2000), which was based on his short story Memento Mori. He then became a frequent collaborator with his brother, Christopher Nolan, co-writing films like The Prestige (2006), The Dark Knight (2008), and The Dark Knight Rises (2012). Jonathan also co-wrote Terminator Salvation (2009)."],
            ['name' => 'Matthew McConaughey', 'birthday' => '1969-11-04', 'biography' => "Matthew McConaughey, born in 1969 in Uvalde, Texas, rose to fame in the 1990s with roles in Dazed and Confused (1993), A Time to Kill (1996), and Lone Star (1996). He became known for romantic comedies in the 2000s, including The Wedding Planner (2001) and How to Lose a Guy in 10 Days (2003). In the 2010s, he transitioned to more dramatic roles, earning critical acclaim for The Lincoln Lawyer (2011), Dallas Buyers Club (2013), which won him an Academy Award, and the HBO series True Detective (2014). He also starred in Christopher Nolan's Interstellar (2014)."],
            ['name' => 'Anne Hathaway', 'birthday' => '1982-11-12', 'biography' => "Anne Hathaway, born in 1982 in Brooklyn, New York, gained fame with The Princess Diaries (2001) and its sequel. She later shifted to more mature roles in films like Brokeback Mountain (2005) and Havoc (2005). Hathaway's career evolved with acclaimed performances in Les Misérables (2012) and The Devil Wears Prada (2006), solidifying her status as a versatile actress."],
            ['name' => 'Jessica Chastain', 'birthday' => '1977-03-24', 'biography' => "Jessica Chastain was born in Sacramento, California, and raised in a middle-class family. She discovered dance at nine and performed in Shakespearean productions. Encouraged by a fellow actor, she auditioned for Juilliard, where she earned a scholarship. After graduating, she worked with TV producer John Wells and appeared in his shows. In 2011, she gained widespread recognition with her role in The Help, earning an Oscar nomination for Best Supporting Actress."],
            ['name' => 'Hans Zimmer', 'birthday' => '1957-09-12', 'biography' => "German-born composer Hans Zimmer is known for blending electronic and orchestral music in film scores. He gained fame with Rain Man (1988) and won an Academy Award for The Lion King (1994). Other notable works include Gladiator (2000), Pirates of the Caribbean (2003), and Inception (2010). Zimmer founded a mentoring \"think tank\" that launched the careers of several composers. He has received numerous awards, including a Lifetime Achievement Award from the National Board of Review."],
            ['name' => 'Hoyte Van Hoytema', 'birthday' => '1971-10-04', 'biography' => "Hoyte Van Hoytema is a Dutch-Swedish cinematographer known for his work on The Fighter (2010), Her (2013), Interstellar (2014), and Dunkirk (2017). After being rejected from film school in the Netherlands, he studied in Poland and began his career with documentaries. His breakthrough came with the film Let the Right One In, which led to international recognition."],
            ['name' => 'Lee Smith', 'birthday' => '1960-01-01', 'biography' => "Lee Smith was born in 1960 in Sydney, New South Wales, Australia. He is an editor, known for Inception (2010), Dunkirk (2017) and 1917 (2019). He is married to Kimberly."],
            ['name' => 'Mary Zophres', 'birthday' => '1964-03-23', 'biography' => "Mary Zophres was born on March 23, 1964 in Ft. Lauderdale, Florida, USA. She is a costume designer, known for La La Land (2016), Babylon (2022) and Hail, Caesar! (2016). She has been married to Murray Valeriano since March 9, 2006."],
            ['name' => 'Leonardo DiCaprio', 'birthday' => '1974-11-11', 'biography' => "Leonardo DiCaprio, born in Los Angeles, began his career in TV and low-budget films before rising to fame with Romeo + Juliet (1996) and Titanic (1997). Known for diverse roles in What's Eating Gilbert Grape (1993) and The Basketball Diaries (1995), he became a Hollywood star. Collaborating frequently with Martin Scorsese, his roles in Gangs of New York (2002) and The Departed (2006) cemented his reputation. DiCaprio is also a passionate environmental activist, donating millions to various causes."],
            ['name' => 'Joseph Gordon-Levitt', 'birthday' => '1981-02-17', 'biography' => "Joseph Gordon-Levitt is an actor, filmmaker, and entrepreneur known for 500 Days of Summer, Inception, Looper, and Snowden. He directed Don Jon and created Mr. Corman on Apple TV+. He co-founded hitRECord, an online community for creative collaboration, and advocates for fair pay in the age of artificial intelligence."],
            ['name' => 'Elliot Page', 'birthday' => '1987-02-21', 'biography' => "Elliot Page, born in Halifax, Nova Scotia, began acting at 10, with notable early roles in Pit Pony (1999) and Marion Bridge (2002). They gained recognition for Hard Candy (2005) and Juno (2007), receiving multiple nominations including an Academy Award for Best Actress. Page continued to appear in films like Whip It (2009), Inception (2010), and To Rome with Love (2012). They also starred in The East (2013), alongside Brit Marling and Alexander Skarsgård."],
            ['name' => 'Wally Pfister', 'birthday' => '1961-07-08', 'biography' => "Wally Pfister is an American cinematographer and film director, known for his work with Christopher Nolan, including Memento (2000), Batman Begins (2005), The Dark Knight (2008), and Inception (2010), for which he won an Academy Award for Best Cinematography. He also worked on The Italian Job (2003) and Moneyball (2011). Pfister made his directorial debut with Transcendence (2014), starring Johnny Depp."],
            ['name' => 'Jeffrey Kurland', 'birthday' => '1958-03-24', 'biography' => "Jeffrey Kurland is known for Inception (2010), Dunkirk (2017) and Erin Brockovich (2000)."],
            ['name' => 'Denis Villeneuve', 'birthday' => '1967-10-03', 'biography' => "Denis Villeneuve is a French Canadian film director and writer. He was born in 1967, in Trois-Rivières, Québec, Canada. He started his career as a filmmaker at the National Film Board of Canada. He is best known for his feature films Arrival (2016), Sicario (2015), Prisoners (2013), Enemy (2013), and Incendies (2010). He is married to Tanya Lapointe."],
            ['name' => 'Jon Spaihts', 'birthday' => '1970-02-09', 'biography' => "Jon Spaihts is an American screenwriter and author. He has written the films Dune starring Timothée Chalamet and Zendaya, Doctor Strange starring Benedict Cumberbatch, The Mummy starring Tom Cruise and Sofia Boutella, Passengers starring Jennifer Lawrence and Chris Pratt, Prometheus starring Michael Fassbender and The Darkest Hour. He is married to Johanna Watts."],
            ['name' => 'Timothée Chalamet', 'birthday' => '1995-12-27', 'biography' => "Timothée Chalamet, born in Manhattan, is an actor known for his breakout role in Call Me by Your Name (2017), which earned him an Academy Award nomination. He started in commercials and theatre before starring in Interstellar (2014) and films like Lady Bird (2017) and Beautiful Boy (2018). Chalamet has also appeared in Little Women (2019) and The King (2019), solidifying his place as one of Hollywood's most acclaimed young actors."],
            ['name' => 'Rebecca Ferguson', 'birthday' => '1983-10-19', 'biography' => "Rebecca Ferguson is a Swedish actress, born in Stockholm, with a British mother and a Swedish father. She gained early fame with the soap opera Nya tider (1999) and later starred in The White Queen (2013), earning a Golden Globe nomination. Ferguson's breakout Hollywood role came in Mission: Impossible – Rogue Nation (2015), where she played Ilsa Faust, a role she reprised in Mission: Impossible – Fallout (2018). She has also starred in The Greatest Showman (2017), Dune (2021), and The Girl on the Train (2016), among other films."],
            ['name' => 'Zendaya', 'birthday' => '1996-09-01', 'biography' => "Zendaya is an American actress, singer, and producer, known for her roles in Shake It Up (2010), K.C. Undercover (2015), Spider-Man: Homecoming (2017), and The Greatest Showman (2017). She earned a Primetime Emmy Award for her role in Euphoria as Rue Bennett. Beyond acting, Zendaya is a fashion designer and singer, with a successful career in music and a clothing line called Daya by Zendaya."],
            ['name' => 'Greig Fraser', 'birthday' => '1975-10-03', 'biography' => "Greig Fraser was born on 3 October 1975 in Melbourne, Australia. He is a cinematographer and producer, known for Dune: Part One (2021), Rogue One: A Star Wars Story (2016) and Zero Dark Thirty (2012). He is married to Jodie Fried. They have three children."],
            ['name' => 'Joe Walker', 'birthday' => '1963-10-02', 'biography' => "Joe Walker is a British film editor who won the 2022 Academy Award for Dune. He has also been nominated for 12 Years a Slave, Arrival, and Blade Runner 2049. Walker won the European Film Award in 2012 for Shame and the American Cinema Editor's Award in 2016 for Arrival. He also edited Widows (2018) and is working on Dune: Part Two."],
            ['name' => 'Bob Morgan', 'birthday' => '1958-01-01', 'biography' => "Bob Morgan is known for Dune: Part One (2021), Maleficent: Mistress of Evil (2019) and Inception (2010)."],
            //['name' => '', 'birthday' => '', 'biography' => ""],
            ['name' => 'The Director', 'birthday' => '2003-06-11', 'biography' => "Born in Chennai. Lives in Germany. Is a German. IBCG - Indian Born Confused German"]
        ];
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('person')->truncate();
        foreach ($data as $person) {
            DB::table('person')->updateOrInsert(
                ['name' => $person['name']], //Condition based on name 
                $person //Data to insert/update
            );
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}